// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	models "github.com/sriharivishnu/shopify-challenge/models/api"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// WeatherLayer is an autogenerated mock type for the WeatherLayer type
type WeatherLayer struct {
	mock.Mock
}

// FetchWeather provides a mock function with given fields: city
func (_m *WeatherLayer) FetchWeather(city string) (models.WeatherResponse, error) {
	ret := _m.Called(city)

	var r0 models.WeatherResponse
	if rf, ok := ret.Get(0).(func(string) models.WeatherResponse); ok {
		r0 = rf(city)
	} else {
		r0 = ret.Get(0).(models.WeatherResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWeatherLayer creates a new instance of WeatherLayer. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewWeatherLayer(t testing.TB) *WeatherLayer {
	mock := &WeatherLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
